---
- name: Install BigCouch
  yum:
    name: kazoo-bigcouch
    state: latest

- name: Start and Enable BigCouch
  service:
    name: kazoo-bigcouch
    state: started
    enabled: yes

- name: Allow BigCouch Port 5984
  firewalld:
    port: 5984/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Bigcouch Port 5986
  firewalld:
    port: 5986/tcp
    permanent: true
    immediate: true
    state: enabled

