---
- name: Install BigCouch
  yum:
    name: kazoo-bigcouch
    state: latest
  notify: Restart BigCouch

- name: Set BigCouch Admin Password Hash Fact
  shell: "echo -n {{ couch_password }}salt | sha1sum | awk '{print \"-hashed-\"$1\",salt\"}'"
  register: couch_hash
  changed_when: false
  check_mode: no

- name: Create BigCouch local.ini
  template:
    src: local.ini.j2
    dest: /etc/kazoo/bigcouch/local.ini
    owner: bigcouch
  notify: Restart BigCouch

- name: Start and Enable BigCouch
  service:
    name: kazoo-bigcouch
    state: started
    enabled: yes

- name: Create BigCouch vm.args
  template:
    src: vm.args.j2
    dest: /etc/kazoo/bigcouch/vm.args
    owner: bigcouch
  notify: Restart BigCouch

- name: Cluster BigCouch
  couchcluster:
    current_node: "{{ ansible_fqdn }}"  
    node_1: "{{ groups['bigcouch'][0] }}"

