---
- include_vars: secrets.yml

- name: Install BigCouch
  yum:
    name: kazoo-bigcouch
    state: latest

- name: Set BigCouch Admin Password Hash Fact
  shell: "echo -n {{ couch_password }}salt | sha1sum | awk '{print \"-hashed-\"$1\",salt\"}'"
  register: couch_hash
  changed_when: false

- name: Create BigCouch local.ini
  template:
    src: local.ini.j2
    dest: /etc/kazoo/bigcouch/local.ini
    owner: bigcouch
  notify: Restart BigCouch

- name: Start and Enable BigCouch
  service:
    name: kazoo-bigcouch
    state: started
    enabled: yes

- name: Create BigCouch vm.args
  template:
    src: vm.args.j2
    dest: /etc/kazoo/bigcouch/vm.args
    owner: bigcouch
  notify: Restart BigCouch

- name: Allow BigCouch Port 5984
  firewalld:
    port: 5984/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow BigCouch Port 5986
  firewalld:
    port: 5986/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow epmd Port
  firewalld:
    port: 4369/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Distributed Erlang Ports
  firewalld:
    port: 11500-11999/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Cluster BigCouch
  couchcluster:
      node_1: "{{ groups['bigcouch'][0] }}"

