---
- name: Restart Kazoo
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
   - kazoo-applications
   - kazoo-ecallmgr

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

