---
- name: Restart HAProxy
  service:
    name: kazoo-haproxy
    state: restarted

- name: Restart Kazoo
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
   - kazoo-applications
   - kazoo-ecallmgr

