---
- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create monsterui.conf
  template:
    src: monsterui.conf.j2
    dest: /etc/nginx/conf.d/monsterui.conf
  notify: Restart Nginx

- name: Install MonsterUI
  yum:
    name: monster-ui*
    state: latest

