---
- name: Install HAProxy
  yum:
    name: kazoo-haproxy
    state: latest

- name: Start and Enable HAProxy
  service:
    name: kazoo-haproxy
    state: started
    enabled: yes

- name: Create HAProxy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/kazoo/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Install Kazoo
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - kazoo-applications
   - kazoo-application-*

- name: Start and Enable Kazoo Applications
  service:
    name: kazoo-applications
    state: started
    enabled: yes

- name: Start and Enable ecallmgr
  service:
    name: kazoo-ecallmgr
    state: started
    enabled: yes

- name: Create Kazoo config.ini
  template:
    src: config.ini.j2
    dest: /etc/kazoo/core/config.ini
  notify: Restart Kazoo

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Install MonsterUI
  yum:
    name: monster-ui*
    state: latest

- name: Create MonsterUI config.js
  template:
    src: config.js.j2
    dest: /var/www/html/monster-ui/js/config.js

