---
- name: Install HAProxy
  yum:
    name: kazoo-haproxy
    state: latest

- name: Start and Enable HAProxy
  service:
    name: kazoo-haproxy
    state: started
    enabled: yes

- name: Create HAProxy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/kazoo/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Install Kazoo
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - kazoo-applications
   - kazoo-application-*

- name: Start and Enable Kazoo Applications
  service:
    name: kazoo-applications
    state: started
    enabled: yes

- name: Start and Enable ecallmgr
  service:
    name: kazoo-ecallmgr
    state: started
    enabled: yes

