---
- name: Install Kazoo
  yum:
    name: {{ item }}
    state: latest
  with_items:
   - kazoo-applications
   - kazoo-application-*

- name: Start and Enable Kazoo Applications
  service:
    name: kazoo-applications
    state: started
    enabled: yes

- name: Start and Enable ecallmgr
  service:
    name: kazoo-ecallmgr
    state: started
    enabled: yes

