---
- name: Install Kazoo RabbitMQ
  become: true
  yum:
    name: kazoo-rabbitmq
    state: latest
- name: Start and Enable Kazoo RabbitMQ Service
  become: true
  service:
    name: kazoo-rabbitmq
    state: started
    enabled: yes

