---
- name: Install Kamailio
  become: true
  yum:
    name: kazoo-kamailio
    state: installed
  notify: Restart Kamailio

- name: Start and Enable Kamailio
  become: true
  service:
    name: kamailio
    state: started
    enabled: yes

- name: Create Kamailio local.cfg
  become: true
  template:
    src: local.cfg.j2
    dest: /etc/kazoo/kamailio/local.cfg
  notify: Restart Kamailio

