---
- name: Install Kamailio
  yum:
    name: kazoo-kamailio
    state: latest
  notify: Restart Kamailio

- name: Start and Enable Kamailio
  service:
    name: kazoo-kamailio
    state: started
    enabled: yes

- name: Create Kamailio local.cfg
  template:
    src: local.cfg.j2
    dest: /etc/kazoo/kamailio/local.cfg
  notify: Restart Kamailio

