---
- name: Set System Time to UTC
  timezone:
    name: UTC

- name: Install 2600hz Stable Repo
  yum:
    name: https://packages.2600hz.com/centos/7/stable/2600hz-release/4.0/2600hz-release-4.0-3.el7.centos.noarch.rpm
    state: installed

- name: Install Delta RPMs
  yum:
    name: deltarpm
    state: latest

- name: Install Yum Utils
  yum:
    name: yum-utils
    state: latest

